seed: -1

clip_observations: 5.0
clip_actions: 1.0

point_cloud:
  use_point_cloud: False
policy: # only works for MlpPolicy right now
  pi_hid_sizes: [512, 256, 128]
  vf_hid_sizes: [512, 256, 128]
  activation: elu # can be elu, relu, selu, crelu, lrelu, tanh, sigmoid
learn:
  agent_name: shadow_hand
  test: False
  resume: 0
  save_interval: 200 # check for potential saves every this many iterations
  print_log: True
  
  # rollout params
  max_iterations: 61040

  # training params
  cliprange: 0.2
  ent_coef: 0
  nsteps: 20
  noptepochs: 5
  nminibatches: 4 # this is per agent
  max_grad_norm: 1
  optim_stepsize: 3.e-4 # 3e-4 is default for single agent training with constant schedule
  schedule: adaptive # could be adaptive or linear or fixed
  desired_kl: 0.016
  gamma: 0.99
  lam: 0.95
  init_noise_std: 0.8

  log_interval: 1
  asymmetric: False